### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by andrianarivo** [tumainimaganiko/Leaderboard#5]
Hi @tumainimaganiko , good job so far on the Leaderboard project. Below are some ideas and suggestions about the project, cheers! 👍🏽

HIGHLIGHTS 🎯

1. The project is well structured and organised into folders/directories ✅
2. The project has a comprehensive README documentation ✅
3. The project has been deployed properly and is accessible viewed via the demo link provided ✅
4. The project is very readable and easy to maintain due to the use of ES6 modules 🥇

RECOMMENDATIONS 🤔

- more descriptive variable names could improve readability
- could include a window.reload(); or event handler DOMContentLoaded upon clicking the submit button to automatically reload the form values in the list
- you could improve the README file with a decriptive features section
- you can deploy your app for a higher level of professionalism
- could include description on the about section of your GitHub page
- perhaps variables can be declared in the global scope for more efficiency

**Comment by tumainimaganiko** [comment]
Hi 👋  @andrianarivo  , thanks so much for your suggestions. I have implemented all the suggestions and added some other interesting features 😊😊. Feel free to open a new issue again.
